### ISSUE TITLE
报regeneratorRuntime is not defined 错误

### ISSUE THREAD

**Issue by wry5560** [songzhengxu/react-starter-kit#1]
Hi~ 我在使用中编译报了regeneratorRuntime is not defined错误，webpack里加上了babel-polyfill。
你这个脚手架使用中没这个错误吗？

**Comment by songzhengxu** [comment]
没有哟，请描述一下你的使用环境，系统，是否修改了哪些东西？

**Comment by wry5560** [comment]
windows系统，没改什么，中间使用了generator函数报错。网上搜是因为bable编译的时候新的API是不转换的，要用babel-polyfill

**Comment by songzhengxu** [comment]
明白了，我更新一下，你也可以先自行修改:
`npm install --save babel-polyfill`
并且在 src 下的index.jsx 添加:
`import 'babel-polyfill';`

**Comment by wry5560** [comment]
已修改
